# NumPy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([1,5,77,97])

In [3]:
myarr

array([ 1,  5, 77, 97])

In [4]:
myarr2 = np.array([34,87,26,76], np.int8)

In [5]:
myarr2

array([34, 87, 26, 76], dtype=int8)

In [6]:
my2darr = np.array([[14,24,35,67]], np.int8)

In [7]:
my2darr

array([[14, 24, 35, 67]], dtype=int8)

In [8]:
myarr[0]

1

In [9]:
my2darr[0]

array([14, 24, 35, 67], dtype=int8)

In [10]:
my2darr[(0,1)]

24

In [11]:
myarr.shape

(4,)

In [12]:
my2darr.shape

(1, 4)

In [13]:
my2darr[0,1]

24

In [14]:
myarr.dtype

dtype('int32')

In [15]:
myarr2.dtype

dtype('int8')

In [16]:
my2darr.dtype

dtype('int8')

In [17]:
myarr[0,1]

IndexError: too many indices for array

In [18]:
my2darr[0,1] = 99

In [19]:
my2darr

array([[14, 99, 35, 67]], dtype=int8)

In [20]:
np.linspace(1,5,2)

array([1., 5.])

In [21]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

# Array Creation Methods

In [22]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [23]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [24]:
listarray.shape

(3, 3)

In [25]:
listarray.size

9

In [26]:
listarray.dtype

dtype('int32')

> array from a set

In [27]:
np.array({3,23,23})

array({3, 23}, dtype=object)

> Intrinsic NumPy Array

In [29]:
zeros = np.zeros((2,5))

In [30]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
zeros.dtype

dtype('float64')

In [32]:
zeros.shape

(2, 5)

In [33]:
rng = np.arange(15)

In [34]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace = np.linspace(1,5,12)

In [37]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [39]:
np.linspace(1,5,2)

array([1., 5.])

In [40]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [41]:
np.linspace(1,5,3)

array([1., 3., 5.])

> empty


In [42]:
emp = np.empty((4,6))

In [43]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.86921143e-306, 1.95819673e-306, 1.42419938e-306],
       [7.56603881e-307, 8.45603441e-307, 1.42417221e-306,
        1.60219306e-306, 6.23059726e-307, 1.06811422e-306],
       [1.42417221e-306, 1.37961641e-306, 6.23039354e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        1.33511562e-306, 6.89805151e-307, 2.56765117e-312]])

In [44]:
ok = np.array([1,3,57,99])

In [45]:
ok

array([ 1,  3, 57, 99])

In [67]:
np.empty_like(ok)

array([2101611408,        478,          0,          0])

In [72]:
ide = np.identity(5)

In [73]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
ide.shape

(5, 5)

In [75]:
ide.size

25

In [76]:
arr = np.arange(99)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [80]:
arr = arr.reshape(3,33)

In [81]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [82]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [83]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [84]:
arr = arr.ravel()

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# AXIS

In [86]:
X = [[1,2,3],[4,5,6],[7,1,0]]

In [87]:
X

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [88]:
ar = np.array(X)

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar.sum()

29

In [91]:
ar.sum(axis=0)

array([12,  8,  9])

In [92]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [93]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [94]:
ar.flat

In [95]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [96]:
ar.ndim

2

In [97]:
ar.size

9

In [98]:
ar.nbytes

36

In [99]:
one = np.array([1,3,4,634,2])

In [100]:
one.argmax()

3

In [101]:
one.argmin()

0

In [102]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [103]:
ar.argmin()

8

In [104]:
ar.argmax()

6

In [105]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [106]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [107]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [108]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [109]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [110]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [111]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [112]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [113]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [115]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [116]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [117]:
[34, 324] + [546, 34]

[34, 324, 546, 34]

> Elementwise Multiplication and it isn't Matrix Multiplication

In [118]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [119]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [120]:
ar.sum()

29

In [121]:
ar.max()

7

In [122]:
ar.min()

0

> Find an element in Array

In [123]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [124]:
type(np.where(ar>5))

tuple

In [125]:
np.count_nonzero(ar)

8

In [126]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [127]:
ar[1,2] = 0

In [128]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [129]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)

> Size of Python Array

In [130]:
sys.getsizeof(1)*len(py_ar)

112

> Size of NumPy Array

In [132]:
np_ar.itemsize * np_ar.size

16

> Size of NumPy Array is much less than a similar Python Array 

> Therefore, it is better to use a NumPy Array instead of Python Array. The major reason is because it saves us a lot of memory.

* Convert a NumPy Array to a Python List

In [135]:
np_ar.tolist()

[0, 4, 55, 2]

*** NumPy Tutorial Completed, enough for us. *** 